"""add sex to users, add bodyweight_logs table

Revision ID: 16e953995612
Revises: ae9a49e90815
Create Date: 2026-07-15 12:12:32.982086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16e953995612'
down_revision: Union[str, Sequence[str], None] = 'ae9a49e90815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bodyweight_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bodyweight_logs_id'), 'bodyweight_logs', ['id'], unique=False)
    op.create_index(op.f('ix_bodyweight_logs_user_id'), 'bodyweight_logs', ['user_id'], unique=False)
    sex_enum = sa.Enum('male', 'female', name='sex')
    sex_enum.create(op.get_bind())
    op.add_column('users', sa.Column('sex', sex_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sex')
    sa.Enum(name='sex').drop(op.get_bind())
    op.drop_index(op.f('ix_bodyweight_logs_user_id'), table_name='bodyweight_logs')
    op.drop_index(op.f('ix_bodyweight_logs_id'), table_name='bodyweight_logs')
    op.drop_table('bodyweight_logs')
    # ### end Alembic commands ###
