"""add unique constraint on bodyweight_logs user_id+date

Revision ID: 77614ebc203f
Revises: 16e953995612
Create Date: 2026-07-15 12:55:51.321506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77614ebc203f'
down_revision: Union[str, Sequence[str], None] = '16e953995612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_bodyweight_logs_user_date', 'bodyweight_logs', ['user_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_bodyweight_logs_user_date', 'bodyweight_logs', type_='unique')
    # ### end Alembic commands ###
