"""add created_by_user_id to exercises for custom exercises

Revision ID: a2d94014f602
Revises: 77614ebc203f
Create Date: 2026-07-15 13:58:28.871283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2d94014f602'
down_revision: Union[str, Sequence[str], None] = '77614ebc203f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_exercises_created_by_user_id'), 'exercises', ['created_by_user_id'], unique=False)
    op.create_foreign_key(None, 'exercises', 'users', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.drop_index(op.f('ix_exercises_created_by_user_id'), table_name='exercises')
    op.drop_column('exercises', 'created_by_user_id')
    # ### end Alembic commands ###
